# Name Service
spring:
  application:
    name: retrieve-videos-service

# Port Service
server:
  port: 8024

# API URL
resource:
  api:
    url: 
      base: https://api.themoviedb.org/3/movie/
      image: https://image.tmdb.org/t/p/w500
    key: "?api_key=0a2eea61408ba5facdd057f7d11d2f58"
    language: "&language=fr-FR"

# DEBUG    
debug: true

# LOG
#logging:
#  path: /var/log/retrieve-videos-service/
#  file: /var/log/retrieve-videos-service/retrieve-videos-service.log

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      